# Generated by Django 4.1.7 on 2023-03-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagram_name", models.CharField(max_length=15)),
                ("fields", models.CharField(default="", max_length=5000)),
                ("ready", models.BooleanField(default=False)),
            ],
        ),
    ]
