# Generated by Django 4.1.7 on 2023-03-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=15)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Diagrams",
            new_name="Diagram",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="chosen_diagram",
        ),
    ]
