# Generated by Django 4.1.7 on 2023-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_delete_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagram",
            name="fields",
            field=models.CharField(default="", max_length=5000),
            preserve_default=False,
        ),
    ]
